
# tasks:
#   - init: npm installks:
#   - init: npm install
#     command: npm run start



vscode:
  extensions:
    - rangav.vscode-thunder-clientod.io/docs/introduction/learn-gitpod/gitpod-yaml)
# and commit this file to your remote git repository to share the goodness with others.

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

tasks:
  - init: npm install
    command: npm run start


